version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0

workflows:
  build-and-test:
    jobs:
      - cimg-steps

jobs:
  cimg-steps:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: deps
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: lint
          command: |
            source .venv/bin/activate
            echo "Running linter..."
      - run:
          name: test
          command: |
            source .venv/bin/activate
            echo "Running tests..."
      - run:
          name: docker_build
          command: |
            docker build -t astachow/2026_l_ii_nph_infi_k1a:latest .
      - run:
          name: docker_push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
            docker push astachow/2026_l_ii_nph_infi_k1a:latest